### ISSUE TITLE
explain mipmap-vs-drawable-folders

### ISSUE THREAD

**Issue by praveen-garg** [mshariq-nerd/NewsReader#4]

**Comment by mshariqaftab** [comment]
> It’s best practice to place your app icons in mipmap- folders (not the drawable- folders) because they are used at resolutions different from the device’s current density.

The mipmap folders are for placing your app/launcher icons (which are shown on the homescreen) in only. Any other drawable assets you use should be placed in the relevant drawable folders as before.

According to this [Google blogpost](http://android-developers.blogspot.in/2014/10/getting-your-apps-ready-for-nexus-6-and.html)
